### ISSUE TITLE
Crash on compilation for a multiline expression

### ISSUE THREAD

**Issue by miconda** [albertodemichelis/squirrel#90]
I tried to embed the squirrel interpreter and got a crash when the script has something like next:
```
			KSR.dbg("request from blocked IP - " + KSR.pv.get("$rm")
					+ " from " + KSR.pv.get("$fu") + " (IP:"
					+ KSR.pv.get("$si") + ":" + KSR.pv.get("$sp") + ")\n");
```

I am not sure if multiline expressions/statements are supposed to work, given that I saw in the docs that end of line marks the end of statement as alternative to `;`, but I supposed this situation should be handled to avoid a crash. `KSR` is a table of functions exported from my application, the script is an attempt of port from JavaScript where multiline statements are supported.

It is interesting that if I changed in the second line in the snippet from:

```
					+ " from " + KSR.pv.get("$fu") + " (IP:"
```
to
```
					+ " xfrom " + KSR.pv.get("$fu") + " (IP:"
```
(note the extra character `x` in front of `from`), the crash didn't happen.

The version used is 3.1, downloaded from sourceforge.

GDB backtrace is:

```
#0  SQStringTable::Add (this=0x1657ec0, news=0x1683d10 " from ", len=6) at sqstate.cpp:598
#1  0x00007fd1e3277869 in SQString::Create (ss=<optimized out>, s=<optimized out>, len=<optimized out>) at sqobject.cpp:51
#2  0x00007fd1e3272625 in SQFuncState::CreateString (this=0x16a4590, s=<optimized out>, len=<optimized out>)
    at sqfuncstate.cpp:584
#3  0x00007fd1e32658b2 in SQCompiler::Factor (this=this@entry=0x7ffe6dcf18d0) at sqcompiler.cpp:717
#4  0x00007fd1e326667a in SQCompiler::PrefixedExpr (this=this@entry=0x7ffe6dcf18d0) at sqcompiler.cpp:613
#5  0x00007fd1e3266e06 in SQCompiler::MultExp (this=0x7ffe6dcf18d0) at sqcompiler.cpp:603
#6  0x00007fd1e326792b in INVOKE_EXP<void (SQCompiler::*)()> (
    f=(void (SQCompiler::*)(SQCompiler * const)) 0x7fd1e3266df0 <SQCompiler::MultExp()>, this=0x7ffe6dcf18d0)
    at sqcompiler.cpp:460
#7  BIN_EXP<void (SQCompiler::*)()> (op3=0, 
    f=(void (SQCompiler::*)(SQCompiler * const)) 0x7fd1e3266df0 <SQCompiler::MultExp()>, op=<optimized out>, 
    this=0x7ffe6dcf18d0) at sqcompiler.cpp:466
#8  PlusExp (this=0x7ffe6dcf18d0) at sqcompiler.cpp:596
#9  ShiftExp (this=0x7ffe6dcf18d0) at sqcompiler.cpp:557
#10 SQCompiler::CompExp (this=0x7ffe6dcf18d0) at sqcompiler.cpp:544
#12 BitwiseAndExp (this=0x7ffe6dcf18d0) at sqcompiler.cpp:527
#13 SQCompiler::BitwiseXorExp (this=0x7ffe6dcf18d0) at sqcompiler.cpp:520
#14 0x00007fd1e32684aa in BitwiseOrExp (this=0x7ffe6dcf18d0) at sqcompiler.cpp:513
#15 SQCompiler::LogicalAndExp (this=0x7ffe6dcf18d0) at sqcompiler.cpp:490
#16 0x00007fd1e326963f in LogicalOrExp (this=0x7ffe6dcf18d0) at sqcompiler.cpp:472
#17 SQCompiler::Expression (this=this@entry=0x7ffe6dcf18d0) at sqcompiler.cpp:377
#18 0x00007fd1e3266782 in FunctionCallArgs (this=0x7ffe6dcf18d0) at sqcompiler.cpp:922
#19 SQCompiler::PrefixedExpr (this=this@entry=0x7ffe6dcf18d0) at sqcompiler.cpp:705
#20 0x00007fd1e3267796 in MultExp (this=0x7ffe6dcf18d0) at sqcompiler.cpp:603
#21 PlusExp (this=0x7ffe6dcf18d0) at sqcompiler.cpp:593
#22 ShiftExp (this=0x7ffe6dcf18d0) at sqcompiler.cpp:557
#23 SQCompiler::CompExp (this=0x7ffe6dcf18d0) at sqcompiler.cpp:544
#24 0x00007fd1e32680cd in EqExp (this=0x7ffe6dcf18d0) at sqcompiler.cpp:534
#25 BitwiseAndExp (this=0x7ffe6dcf18d0) at sqcompiler.cpp:527
#26 SQCompiler::BitwiseXorExp (this=0x7ffe6dcf18d0) at sqcompiler.cpp:520
#27 0x00007fd1e32684aa in BitwiseOrExp (this=0x7ffe6dcf18d0) at sqcompiler.cpp:513
#28 SQCompiler::LogicalAndExp (this=0x7ffe6dcf18d0) at sqcompiler.cpp:490
#29 0x00007fd1e326963f in LogicalOrExp (this=0x7ffe6dcf18d0) at sqcompiler.cpp:472
#30 SQCompiler::Expression (this=this@entry=0x7ffe6dcf18d0) at sqcompiler.cpp:377
---Type <return> to continue, or q <return> to quit---
#31 0x00007fd1e326a7b2 in SQCompiler::CommaExpr (this=0x7ffe6dcf18d0) at sqcompiler.cpp:369
#32 0x00007fd1e326c610 in SQCompiler::Statement (this=this@entry=0x7ffe6dcf18d0, closeframe=closeframe@entry=true)
    at sqcompiler.cpp:311
#33 0x00007fd1e326eb30 in Statements (this=0x7ffe6dcf18d0) at sqcompiler.cpp:205
#34 IfBlock (this=0x7ffe6dcf18d0) at sqcompiler.cpp:1037
#35 SQCompiler::IfStatement (this=this@entry=0x7ffe6dcf18d0) at sqcompiler.cpp:1063
#36 0x00007fd1e326b93c in SQCompiler::Statement (this=this@entry=0x7ffe6dcf18d0, closeframe=closeframe@entry=true)
    at sqcompiler.cpp:214
#37 0x00007fd1e326eb30 in Statements (this=0x7ffe6dcf18d0) at sqcompiler.cpp:205
#38 IfBlock (this=0x7ffe6dcf18d0) at sqcompiler.cpp:1037
#39 SQCompiler::IfStatement (this=this@entry=0x7ffe6dcf18d0) at sqcompiler.cpp:1063
#40 0x00007fd1e326b93c in SQCompiler::Statement (this=this@entry=0x7ffe6dcf18d0, closeframe=closeframe@entry=true)
    at sqcompiler.cpp:214
#41 0x00007fd1e326bbb0 in Statements (this=0x7ffe6dcf18d0) at sqcompiler.cpp:205
#42 SQCompiler::Statement (this=this@entry=0x7ffe6dcf18d0, closeframe=closeframe@entry=false) at sqcompiler.cpp:279
#43 0x00007fd1e3265499 in SQCompiler::CreateFunction (this=this@entry=0x7ffe6dcf18d0, name=..., lambda=lambda@entry=false)
    at sqcompiler.cpp:1522
#44 0x00007fd1e326bf84 in FunctionStatement (this=0x7ffe6dcf18d0) at sqcompiler.cpp:1281
#45 SQCompiler::Statement (this=this@entry=0x7ffe6dcf18d0, closeframe=closeframe@entry=true) at sqcompiler.cpp:268
#46 0x00007fd1e326db3e in SQCompiler::Compile (this=this@entry=0x7ffe6dcf18d0, o=...) at sqcompiler.cpp:180
#47 0x00007fd1e3264dc2 in Compile (vm=vm@entry=0x167e620, rg=0x7fd1e3291ae0 <_io_file_lexfeed_PLAIN(void*)>, up=0x7ffe6dcf1c50, 
    sourcename=0x7fd1e8754a88 "./misc/examples/kemi/kamailio-basic-kemi-sqlang.sq", out=..., raiseerror=<optimized out>, 
    lineinfo=true) at sqcompiler.cpp:1575
#48 0x00007fd1e325d4ea in sq_compile (v=0x167e620, read=<optimized out>, p=<optimized out>, sourcename=<optimized out>, 
    raiseerror=<optimized out>) at sqapi.cpp:131

```

**Comment by albertodemichelis** [comment]
I think you might have something related to you application, this expression is quite trivial, I'm pretty sure is not a problem in the compiler. I tried to compile it with sq from squirrel 3.1 and it compiles just fine.

**Comment by miconda** [comment]
Thanks, I will try to see if goes ok with the squirrel compiler alone. For reference, the script I tried to compile is:

  * https://github.com/kamailio/kamailio/blob/master/misc/examples/kemi/kamailio-basic-kemi-sqlang.sq

**Comment by albertodemichelis** [comment]
It compiles fine for me

**Comment by miconda** [comment]
Thanks for your time, also compiles fine for me with sq.

I am closing this one, it seems to be related to #91 -- I am digging more into that one.
